// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.idealo.mapping.content.domain;

import de.idealo.mapping.content.domain.Mapping;
import de.idealo.mapping.content.domain.MappingDataOnDemand;
import de.idealo.mapping.content.domain.MappingIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MappingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MappingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MappingIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MappingIntegrationTest: @Transactional;
    
    @Autowired
    MappingDataOnDemand MappingIntegrationTest.dod;
    
    @Test
    public void MappingIntegrationTest.testCountMappings() {
        Assert.assertNotNull("Data on demand for 'Mapping' failed to initialize correctly", dod.getRandomMapping());
        long count = Mapping.countMappings();
        Assert.assertTrue("Counter for 'Mapping' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MappingIntegrationTest.testFindMapping() {
        Mapping obj = dod.getRandomMapping();
        Assert.assertNotNull("Data on demand for 'Mapping' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Mapping' failed to provide an identifier", id);
        obj = Mapping.findMapping(id);
        Assert.assertNotNull("Find method for 'Mapping' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Mapping' returned the incorrect identifier", id, obj.getId_());
    }
    
    @Test
    public void MappingIntegrationTest.testFindAllMappings() {
        Assert.assertNotNull("Data on demand for 'Mapping' failed to initialize correctly", dod.getRandomMapping());
        long count = Mapping.countMappings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Mapping', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Mapping> result = Mapping.findAllMappings();
        Assert.assertNotNull("Find all method for 'Mapping' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Mapping' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MappingIntegrationTest.testFindMappingEntries() {
        Assert.assertNotNull("Data on demand for 'Mapping' failed to initialize correctly", dod.getRandomMapping());
        long count = Mapping.countMappings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Mapping> result = Mapping.findMappingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Mapping' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Mapping' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MappingIntegrationTest.testFlush() {
        Mapping obj = dod.getRandomMapping();
        Assert.assertNotNull("Data on demand for 'Mapping' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Mapping' failed to provide an identifier", id);
        obj = Mapping.findMapping(id);
        Assert.assertNotNull("Find method for 'Mapping' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMapping(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Mapping' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MappingIntegrationTest.testMergeUpdate() {
        Mapping obj = dod.getRandomMapping();
        Assert.assertNotNull("Data on demand for 'Mapping' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Mapping' failed to provide an identifier", id);
        obj = Mapping.findMapping(id);
        boolean modified =  dod.modifyMapping(obj);
        Integer currentVersion = obj.getVersion();
        Mapping merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId_(), id);
        Assert.assertTrue("Version for 'Mapping' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MappingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Mapping' failed to initialize correctly", dod.getRandomMapping());
        Mapping obj = dod.getNewTransientMapping(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Mapping' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Mapping' identifier to be null", obj.getId_());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Mapping' identifier to no longer be null", obj.getId_());
    }
    
    @Test
    public void MappingIntegrationTest.testRemove() {
        Mapping obj = dod.getRandomMapping();
        Assert.assertNotNull("Data on demand for 'Mapping' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Mapping' failed to provide an identifier", id);
        obj = Mapping.findMapping(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Mapping' with identifier '" + id + "'", Mapping.findMapping(id));
    }
    
}
