// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.idealo.mapping.content.domain;

import de.idealo.mapping.content.domain.MappingDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MappingDataOnDemand_Roo_Configurable {
    
    declare @type: MappingDataOnDemand: @Configurable;
    
}
